In [8]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesClassifier

In [3]:

df = pd.read_csv('wine_dataset.csv')
df.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [4]:
df['style'] = df['style'].replace('red', 0)
df['style'] = df['style'].replace('white', 1)

In [5]:
df

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,1
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,1
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,1
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,1
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,1

In [6]:
y = df['style']
x = df.drop('style', axis=1)

In [7]:

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [12]:
model = ExtraTreesClassifier()
model.fit(x_train, y_train)

result = model.score(x_test, y_test)
print(f'Accuracy: {result}')

Accuracy: 0.9964102564102564

In [18]:
y_test.iloc[400:413]

1830    1
1882    1
5241    1
5725    1
5007    1
5545    1
2213    1
1191    0
1190    0
6318    1
4385    1
5638    1
4737    1
Name: style, dtype: int64

In [19]:
x_test.iloc[400:413]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
1830,8.3,0.280,0.40,7.8,0.041,38.0,194.0,0.99760,3.34,0.51,9.6,6
1882,6.7,0.340,0.30,15.6,0.054,51.0,196.0,0.99820,3.19,0.49,9.3,5
5241,6.0,0.250,0.40,5.7,0.052,56.0,152.0,0.99398,3.16,0.88,10.5,6
5725,6.3,0.180,0.22,5.6,0.047,45.0,147.0,0.99383,3.09,0.54,10.0,5
5007,7.1,0.320,0.30,9.9,0.041,63.0,192.0,0.99642,3.12,0.49,10.2,6
5545,6.0,0.300,0.33,2.1,0.042,31.0,127.0,0.98964,3.32,0.42,12.5,6
2213,7.5,0.210,0.68,10.9,0.045,38.0,133.0,0.99780,3.00,0.36,8.7,5
1191,6.5,0.885,0.00,2.3,0.166,6.0,12.0,0.99551,3.56,0.51,10.8,5
1190,9.1,0.400,0.57,4.6,0.080,6.0,20.0,0.99652,3.28,0.57,12.5,6
6318,6.7,0.150,0.32,7.9,0.034,17.0,81.0,0.99512,3.29,0.31,10.0,6
4385,8.0,0.300,0.36,11.0,0.034,8.0,70.0,0.99354,3.05,0.41,12.2,6
5638,6.1,1.100,0.16,4.4,0.033,8.0,109.0,0.99058,3.35,0.47,12.4,4
4737,6.9,0.220,0.43,6.4,0.042,34.0,115.0,0.99293,3.05,0.51,10.8,6

In [20]:
predict = model.predict(x_test.iloc[400:413])
predict

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1])